### ISSUE TITLE
trustworthiness p-values identical across multiple datasets and dimensionality reduction algorithms?

### ISSUE THREAD

**Issue by Ebony-Watson** [biomedical-cybernetics/pypsis#7]
Hi,

Great paper! I am hoping to use your metrics to compare t-SNE and UMAP for dimensionality reduction of scRNA-seq datasets. However after running 'indices.compute_trustworthiness' on four different datasets for both algorithms, whilst I get differing values for each of the metrics, the p-value is always 0.16667 no matter what. Is there a reason for this? This is the configuration I am using:

indices.compute_trustworthiness(data_matrix=embedding, sample_labels=labels, positive_classes=None, projection_type='centroid',center_formula='median', iterations=5, seed=1)

Best,
Ebony

**Comment by biomedical-cybernetics** [comment]
Hello Ebony

I guess your problem is related with the number of iterations for shuffling
you used to build the null model.
5 iterations is really low.

Did you study the article well?
The null model is created by shuffling  the labels on the sample
coordinates over the centroid line.
If you have 10 samples you can do 10! permutations.

Read this section of the article and you will understand:

" 2) Trustworthiness: A Statistical Evaluation of Separability Significance
This section introduces a methodological innovation proposed to account for
the uncertainty of the separability estimation. Briefly, we propose a
resampling methodology to build a null model that allows the computation of
an empirical p-value to assess the trustworthiness of the separability
measure provided by a selected index. Trustworthiness assesses the extent
to which a value produced by a certain index is reliable under uncertainty.
The procedure is as follows. For a given DR method result (in a certain
dataset), we freeze the geometrical position of the samples and reshuffle
their group labels uniformly at random. This procedure is repeated 1000
times (we set the default 1000 times because it offers an accurate
estimation of the null model, but this value can also be increased in
relation to the needs of the users), and the value of a certain index is
measured at each round, generating a null model distribution composed of
1000 random values. Subsequently, a p-value (that expresses the extent to
which the true index value can be generated at random) was computed as the
number of random values that surpassed the initial (true) index value.
Thus, for each index, the comparison with the null model is characterized
by the following: a) the mean of the 1000 null model random values, b) the
standard error of the 1000 null model random values, and c) the
separability significance (p-value) to quantify whether the evaluation
provided by the index is significant in comparison to the null model. As
previously reported, and here expressed in a different form, the
separability significance (trustworthiness) represents the fraction of
random reshuffling in which the index behaves better than in the true label
assignment case. In other words, it measures the likelihood that the index
value will be obtained by chance. We considered as significant all the
p-values lower than 0.01 with respect to the null model distribution. "

thanks
best
Carlo

**Comment by Ebony-Watson** [comment]
Hi Carlo, 

Thank you so much for your response, I clearly wasn't paying enough attention to that section!

Best,
Ebony
